tradeLimit = 99999999999999
# Uncomment to enable trade order buy or sell
# firstTrade = "buy"

[sell]
enabled = false
limitPrice = 99999999999999


[stopLoss]
enabled =  false
lessThanOrEqualTo = -99999999999999
pauseOnStopLoss = false


[buy]
enabled = false
limitPrice = -99999999999999


[buyRange]
enabled = false
lessThanOrEqualTo = -99999999999999
greaterThanOrEqualTo = 99999999999999
