
# Tell the bot if the first trade should be a buy or sell
firstTrade = "buy"

shortSize = 9

longSize = 34

rsiSize = 14
rsiSellPoint = 80
initialBuyPrice = 0
buyFee = 0.15
sellFee = 0.15

#Wait 5 candles before performing another advice
candleTradeLag = 5

[WBM1]
