
# Tell the bot if the first trade should be a buy or sell
firstTrade = "buy"

# -1 = no limit
tradeLimit = -1
shortSize = 9
longSize = 34
rsiSize = 14
rsiSellPoint = 80
initialBuyPrice = 0
buyFee = 0.15
sellFee = 0.15
profitMarginPercentage = 2

[WBM1]
